
server:
  port: 8040
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///D:\wzd\localGit # 配置git仓库的地址
          search-paths: config-repo # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: # git仓库的账号
          password: # git仓库的密

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka          