server:
  port: 8020
spring:
  application:
    name: microservice-consumer-movie-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/, http://peer2:8762/eureka/
  instance:
    preferIpAddress: false
